#pragma once
#include <string>

using std::string;

namespace cppengine {
    enum class Keyboard : unsigned short {
        UNKNOWN,

        ESCAPE,
        F1,
        F2,
        F3,
        F4,
        F5,
        F6,
        F7,
        F8,
        F9,
        F10,
        F11,
        F12,

        BACKQUOTE,
        DIGIT_1,
        DIGIT_2,
        DIGIT_3,
        DIGIT_4,
        DIGIT_5,
        DIGIT_6,
        DIGIT_7,
        DIGIT_8,
        DIGIT_9,
        DIGIT_0,
        MINUS,
        EQUAL,
        BACKSPACE,

        TAB,
        KEY_Q,
        KEY_W,
        KEY_E,
        KEY_R,
        KEY_T,
        KEY_Y,
        KEY_U,
        KEY_I,
        KEY_O,
        KEY_P,
        BRACKET_L,
        BRACKER_R,
        BACKSLASH,

        CAPS_LOCK,
        KEY_A,
        KEY_S,
        KEY_D,
        KEY_F,
        KEY_G,
        KEY_H,
        KEY_J,
        KEY_K,
        KEY_L,
        SEMICOLON,
        QUOTE,
        ENTER,

        SHIFT_LEFT,
        KEY_Z,
        KEY_X,
        KEY_C,
        KEY_V,
        KEY_B,
        KEY_N,
        KEY_M,
        COMMA,
        PERIOD,
        SLASH,
        SHIFT_RIGHT,

        CTRL_LEFT,
        META_LEFT,
        ALT_LEFT,
        SPACE,
        ALT_RIGHT,
        FUNCTION,
        META_RIGHT,
        CONTEXT_MENU,
        CONTROL_RIGHT,

        PRINT_SCREEN,
        SCROLL_LOC,
        PAUSE,

        INSERT,
        HOME,
        PAGE_UP,
        DELETE,
        END,
        PAGE_DOWN,

        ARROW_UP,
        ARROW_LEFT,
        ARROW_RIGHT,
        ARROW_DOWN,

        NUM_LOCK,
        NUM_DIVIDE,
        NUM_MULTIPLY,
        NUM_SUBTRACT,
        NUM_ADD,
        NUM_ENTER,
        NUM_DECIMAL,

        NUM_1,
        NUM_2,
        NUM_3,
        NUM_4,
        NUM_5,
        NUM_6,
        NUM_7,
        NUM_8,
        NUM_9,
        NUM_0
    };
}